environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\devtools\\appveyor\\run_with_env.cmd"

  matrix:
    #- PYTHON: "C:\\Python33_32"
    #  PYTHON_VERSION: "3.3"
    #  PYTHON_ARCH: "32"
    #  CONDA_PY: "33"
    #  CONDA_NPY: "19"

    - PYTHON: "C:\\Python34_32"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      CONDA_PY: "34"
      CONDA_NPY: "19"

install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  # as well as pip, conda-build, and the binstar CLI
  - ps: . ".\\devtools\\appveyor\\install.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda config --add channels http://conda.binstar.org/omnia

build: false

test_script:
  - "%CMD_IN_ENV% conda build --quiet devtools\\conda-recipe"
