environment:

  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"


install:
    # Make sure pip is around
  - python -m ensurepip
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    # Add conda-forge channel
  - conda config --add channels conda-forge

    # Add omnia channel
  - conda config --add channels omnia

    # Always run commands without asking
  - conda config --set always_yes yes

    # Try to update conda first to avoid odd dependency clashes
  - conda update --all

    # Create test environment for package
  - python devtools\\scripts\\create_conda_env.py -n=test -p=%PYTHON_VERSION% devtools\\conda-envs\\test_env.yaml

    # Activate the test environment
  - activate test

    # Build and install package
  - python setup.py develop --no-deps


build: false

test_script:
  - pytest -v --cov=openmmtools openmmtools\\tests

on_success:
  - codecov
