package:
  name: openmmtools-dev
  version: 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - openmm
    - parmed
    - netcdf4
    - pymbar

  run:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - six
    - openmm
    - parmed
    - netcdf4
    - pymbar

test:
  requires:
    - nose
  imports:
    - openmmtools

about:
  home: https://github.com/choderalab/openmmtools
  license: MIT License
