package:
  name: openmmtools-dev
  version: 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - openmm >=7.3.1
    - cython

  run:
    - python
    - numpy
    - scipy
    - openmm >=7.3.1
    - mdtraj
    - netcdf4 >=1.4.2 # after bugfix: "always return masked array by default, even if there are no masked values"
    - libnetcdf >=4.6.2 # workaround for libssl issues
    - pyyaml
    - cython
    - sphinxcontrib-bibtex
    - mpiplus
    - pymbar
    - pyyaml
    - numba
    - nose

test:
  requires:
    - nose
    - pymbar
# Until the NetCDF issues are resolved, actual test runs are subject to run_test.[bat,sh] (9/16/2018)
#  imports:
#    - openmmtools

about:
  home: https://github.com/choderalab/openmmtools
  license: MIT License
